name: Performance Testing CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run performance tests daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  performance-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: nextjs-frontend/package-lock.json
    
    - name: Install dependencies
      working-directory: ./nextjs-frontend
      run: npm ci
    
    - name: Install Lighthouse CI
      run: npm install -g @lhci/cli@0.14.x
    
    - name: Build application
      working-directory: ./nextjs-frontend
      run: npm run build
    
    - name: Run bundle analysis
      working-directory: ./nextjs-frontend
      run: npm run perf:bundle
      continue-on-error: true
    
    - name: Start server and run Lighthouse CI
      working-directory: ./nextjs-frontend
      run: |
        npm run start &
        sleep 10
        npm run lighthouse:mobile
      continue-on-error: true
    
    - name: Run Web Vitals tests
      working-directory: ./nextjs-frontend
      run: npm run perf:vitals
      continue-on-error: true
    
    - name: Upload Lighthouse reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lighthouse-reports-${{ matrix.node-version }}
        path: |
          nextjs-frontend/.lighthouseci/
          nextjs-frontend/performance-reports/
        retention-days: 30
    
    - name: Upload bundle analysis
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: bundle-analysis-${{ matrix.node-version }}
        path: |
          nextjs-frontend/bundle-analysis-report.json
          nextjs-frontend/.next/analyze/
        retention-days: 30
    
    - name: Comment PR with performance results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          try {
            const reportPath = path.join(process.cwd(), 'nextjs-frontend/performance-reports/performance-report.json');
            if (fs.existsSync(reportPath)) {
              const report = JSON.parse(fs.readFileSync(reportPath, 'utf8'));
              
              const comment = `
              ## 📊 Performance Test Results
              
              **Summary:**
              - ✅ Passed: ${report.summary.passed}
              - ❌ Failed: ${report.summary.failed}  
              - ⚠️ Warnings: ${report.summary.warnings}
              
              **Bundle Analysis:** ${report.bundleAnalysis?.passed ? '✅ Passed' : '❌ Failed'}
              **Lighthouse Tests:** ${report.lighthouse?.passed ? '✅ Passed' : '❌ Failed'}
              **Web Vitals Tests:** ${report.webVitals?.passed ? '✅ Passed' : '❌ Failed'}
              
              [View detailed reports in artifacts](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
              `;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            }
          } catch (error) {
            console.log('Could not post performance results:', error.message);
          }

  lighthouse-ci:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: nextjs-frontend/package-lock.json
    
    - name: Install dependencies
      working-directory: ./nextjs-frontend
      run: npm ci
    
    - name: Build and test with Lighthouse CI
      working-directory: ./nextjs-frontend
      run: |
        npm run build
        npm run lighthouse
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

  bundle-size-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: nextjs-frontend/package-lock.json
    
    - name: Install dependencies
      working-directory: ./nextjs-frontend
      run: npm ci
    
    - name: Build and analyze bundle
      working-directory: ./nextjs-frontend
      run: |
        npm run build
        npm run analyze
      env:
        ANALYZE: true
    
    - name: Check bundle size
      working-directory: ./nextjs-frontend
      run: npm run perf:bundle
    
    - name: Upload bundle analysis
      uses: actions/upload-artifact@v4
      with:
        name: bundle-analysis
        path: |
          nextjs-frontend/.next/analyze/
          nextjs-frontend/bundle-analysis-report.json